feat(declarative): declarative configuration
webhookx-io/webhookx pull request #68
Opened 2024-12-05 09:33 UTC by vm-001

### Summary

- Introduced declarative configuration.
- Added`admin sync` and `admin dump` commands

Usage

```
$ webhookx admin sync webhookx.sample.yml
$ # equivalent to
$ webhookx admin sync webhookx.sample.yml --timeout 10 --addr http://localhost:8080 --workspace default
```

```
$ webhookx admin dump
$ # equivalent to
$ webhookx admin dump --timeout 10 --addr http://localhost:8080 --workspace default
```

2024-12-12 15:50 UTC, webhookx-x requested changes

2024-12-12 15:50 UTC, webhookx-x commented on admin/api/api.go
> +func (api *API) text(code int, w http.ResponseWriter, bytes []byte) {
I prefer using `string` instead of `[]byte`

2024-12-12 15:50 UTC, webhookx-x commented on admin/api/api.go
> +	r.HandleFunc("/workspaces/{workspace}/dump", api.Dump).Methods("POST")
Can we add a prefix to make these APIs more literal?  like 

`/workspaces/{workspace}/config(declarative)/*`

2024-12-12 15:50 UTC, webhookx-x commented on cmd/admin_dump.go
> +		Short: "Dump WebhookX entities to a declarative configuration",
```suggestion
		Short: "Dump entities to declarative configuration",
```

2024-12-12 15:50 UTC, webhookx-x commented on cmd/root.go
> +	cmd.PersistentFlags().BoolVarP(&verbose, "verbose", "", false, "Verbose logging.")
I don't see this flag being used.

2024-12-12 15:50 UTC, webhookx-x commented on utils/utils.go
> +)
```suggestion
import "reflect"
```

2024-12-12 15:50 UTC, webhookx-x commented on test/cmd/admin_test.go
> +				assert.Equal(GinkgoT(), "", output)
does it need to output anything when sync is successful?

2024-12-12 17:50 UTC, vm-001 commented on cmd/root.go
> +	cmd.PersistentFlags().BoolVarP(&verbose, "verbose", "", false, "Verbose logging.")
fixed

2024-12-24 08:51 UTC, webhookx-x approved these changes

2024-12-24 08:55 UTC, merged